# -*- coding: utf-8 -*-
"""gestionderisque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaeL1gyax8_pqG1NgUblCGUTrUSRXy5F
"""

import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')

# 1. Charger le fichier Excel
file_path = 'base_SNI.xlsx'
df_base = pd.read_excel(file_path, sheet_name='base_sni')

df_base.shape

# Valeurs manquantes
print("\n Valeurs manquantes par variable :")
missing_values = df_base.isnull().sum()
print(missing_values)

print("\n Nombre de lignes dupliquées :")
duplicates = df_base.duplicated().sum()
print(duplicates)

df_base = df_base.drop_duplicates()

print("\n Types de variables :")
print(df_base.dtypes.value_counts())

#Identifier variables numériques vs catégorielles
numeric_cols = df_base.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df_base.select_dtypes(include=['object', 'datetime']).columns.tolist()
print(f"\nVariables numériques ({len(numeric_cols)}) :")
print(numeric_cols)
print(f"\nVariables catégorielles ({len(categorical_cols)}) :")
print(categorical_cols)

# Afficher les valeurs possibles pour chaque variable catégorielle

for col in categorical_cols:
    print(f"\nColonne : {col}")
    print("-" * 40)

    # Valeurs uniques (en excluant les valeurs manquantes)
    unique_values = df_base[col].dropna().unique()

    print(f"Nombre de modalités : {len(unique_values)}")
    print(unique_values)

print("\n Statistiques descriptives (variables numériques) :")
print(df_base[numeric_cols].describe().round(2))

# Afficher les valeurs possibles pour chaque variable numérique

for col in numeric_cols:
    print(f"\nColonne : {col}")
    print("-" * 40)

    # Valeurs uniques (en excluant les valeurs manquantes)
    unique_values = df_base[col].dropna().unique()

    print(f"Nombre de modalités : {len(unique_values)}")
    print(unique_values)

df_base.loc[df_base['Maturite'] < 0, 'Maturite'] = 0
#changer les valeur negative de la colonne maturité par 0

#Vérifier les valeurs négatives pour les variables qui ne devraient pas en avoir
positive_vars = ['CRD', 'PNU', 'nb_pret', 'Garantie_max', 'Revenus_mensuels', 'Engagement']
for var in positive_vars:
    if var in df_base.columns:
        negative_count = (df_base[var] < 0).sum()
        if negative_count > 0:
            print(f"  - {var} : {negative_count} valeurs négatives")

cat_cols = [
    'Pays de domiciliation', 'Etat civil', 'Nationalité', 'Profession',
    'Segmentation commercilale', 'Type de revenu', 'Catégorie sociale',
    'Code tribunal', 'Code localité', 'Interdiction cheque', 'Segment'
]

for col in cat_cols:
    df_base[col] = df_base[col].fillna('Inconnu')

num_cols = [
    'Solde_moyen', 'Revenus_mensuels', 'Solde_arrete',
    'Engagement', 'CRD/eng'
]

for col in num_cols:
    df_base[col] = df_base[col].fillna(df_base[col].median())

df_base = df_base.drop(columns=['Code tribunal'])

df_base.isna().sum()

date_mediane = df_base['Date_naissance'].dropna().median()
df_base['Date_naissance'] = df_base['Date_naissance'].fillna(date_mediane)

df_base.isna().sum()

df_base.hist(figsize=(15,10))
plt.show()

for var in numeric_cols:
  Q1 = df_base[var].quantile(0.25)
  Q3 = df_base[var].quantile(0.75)
  IQR = Q3 - Q1

  outliers = df_base[(df_base[var] < Q1 - 1.5*IQR) |
              (df_base[var] > Q3 + 1.5*IQR)]
  print(f"Nombre d'outliers dans {var} : {len(outliers)}")

for var in numeric_cols:
  sns.boxplot(x=df_base[var])
  plt.show()

for var in ['CRD','Solde_moyen','Revenus_mensuels','Engagement','Solde_arrete']:
    df_base[var] = np.log1p(df_base[var])
#Une transformation logarithmique a été appliquée afin de réduire l’asymétrie et l’impact des valeurs extrêmes

from scipy.stats.mstats import winsorize

df_base['nb_pret_w'] = winsorize(df_base['nb_pret'], limits=[0.01, 0.01])
#La winsorisation consiste à limiter (plafonner) les valeurs extrêmes

cap = df_base['CRD/gar'].quantile(0.99)
df_base['CRD/gar_cap'] = np.minimum(df_base['CRD/gar'], cap)

mask = (df_base['Garantie_max'] == 0) & (df_base['flag_lombard_decouvert'] == 1)
df_base['flag_lombard_corrige'] = mask.astype(int)

df_base.loc[mask, 'flag_lombard_decouvert'] = 0
#Garantie = 0 donc flag_lombard_decouvert = 0

df_base.head(10)

from sklearn.preprocessing import StandardScaler

vars_to_scale = [
    'CRD', 'PNU', 'nb_pret', 'Maturite', 'Garantie_max',
     'Age_relation', 'Solde_moyen',
    'Revenus_mensuels', 'Solde_arrete',
    'Engagement', 'CRD/gar', 'CRD/eng'
]

scaler = StandardScaler()

df_base[vars_to_scale] = scaler.fit_transform(df_base[vars_to_scale])

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Colonnes catégorielles à encoder
categorical_cols = [
    'Pays de domiciliation', 'Etat civil', 'Nationalité', 'Profession',
    'Segmentation commercilale', 'Type de revenu', 'Catégorie sociale',
    'Code localité', 'Interdiction cheque', 'Segment'
]

# Vérifier que ces colonnes existent dans df_base
categorical_cols = [c for c in categorical_cols if c in df_base.columns]

# Encodage
ohe = OneHotEncoder(
    drop='first',            # évite la multicolinéarité
    handle_unknown='ignore', # gère les nouvelles catégories
    sparse_output=False
)

encoded_cat = ohe.fit_transform(df_base[categorical_cols])

# Créer un DataFrame à partir du résultat encodé
encoded_cat_df = pd.DataFrame(
    encoded_cat,
    columns=ohe.get_feature_names_out(categorical_cols),
    index=df_base.index
)

# Concaténer avec les colonnes numériques restantes
df_base = pd.concat(
    [df_base.drop(columns=categorical_cols), encoded_cat_df],
    axis=1
)

print(df_base.dtypes)

df_base['Date_naissance'] = pd.to_datetime(df_base['Date_naissance'])
df_base['date OBSERVATION'] = pd.to_datetime(df_base['date OBSERVATION'])

df_base['Age'] = (
    (df_base['date OBSERVATION'] - df_base['Date_naissance'])
    .dt.days / 365.25
).astype(int)

df_base['Age'] = np.where(
    (df_base['Age'] < 18) | (df_base['Age'] > 85),
    np.nan,
    df_base['Age']
)

df_base['Age'] = df_base['Age'].fillna(df_base['Age'].median())

age_bins = [18, 25, 35, 45, 55, 65, 90]
age_labels = [
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65+'
]

df_base['Age_classe'] = pd.cut(
    df_base['Age'],
    bins=age_bins,
    labels=age_labels,
    right=False
)

# Création de la variable cible flag_defaut
df_base['flag_defaut'] = np.where(df_base['DPD 12M'] > 90, 1, 0)

df_base.isna().sum()

from sklearn.model_selection import train_test_split

# Variable cible
y = df_base['flag_defaut']

# Variables explicatives (on enlève la cible)
X = df_base.drop(columns=['flag_defaut', 'id_tiers', 'code_client','Date_naissance','date OBSERVATION','Age_classe'])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y   # garantit la présence de défauts dans les deux jeux
)

# Train
train_df = pd.concat([X_train, y_train], axis=1)

# Test
test_df = pd.concat([X_test, y_test], axis=1)

!pip install xlsxwriter

with pd.ExcelWriter("train_test_datasets.xlsx", engine="xlsxwriter") as writer:
    train_df.to_excel(writer, sheet_name="Train", index=False)
    test_df.to_excel(writer, sheet_name="Test", index=False)

from google.colab import files
files.download("train_test_datasets.xlsx")

# Afficher le nombre d'observations par classe
print(y.value_counts())

from imblearn.over_sampling import SMOTE

# Impute any remaining NaN values in X_train and X_test
# This step ensures that SMOTE can process the data without errors
X_train = X_train.fillna(X_train.median())
X_test = X_test.fillna(X_test.median())

smote = SMOTE(
    sampling_strategy='auto',  # équilibre 50/50
    random_state=42
)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

X_test_res, y_test_res = smote.fit_resample(X_test, y_test)
# Combiner X_test et y_test rééchantillonnés
test_resampled_df = pd.concat([X_test_res, y_test_res], axis=1)

# Exporter en Excel
test_resampled_df.to_excel("test_resampled.xlsx", index=False)

files.download("test_resampled.xlsx")

import pandas as pd
import numpy as np

def calc_iv(df, feature, target, bins=10):
    """
    Calcule l'Information Value pour une variable continue ou catégorielle.
    """
    lst = []
    df_copy = df.copy()

    # Si variable numérique, on la binne
    if df_copy[feature].dtype.kind in 'bifc':
        df_copy[feature] = pd.qcut(df_copy[feature], q=bins, duplicates='drop')

    for val in df_copy[feature].unique():
        df_val = df_copy[df_copy[feature] == val]
        good = ((df_val[target] == 0).sum()) / ((df_copy[target] == 0).sum())
        bad  = ((df_val[target] == 1).sum()) / ((df_copy[target] == 1).sum())
        woe = np.log((good + 0.0001) / (bad + 0.0001))  # éviter div par 0
        iv = (good - bad) * woe
        lst.append(iv)

    return sum(lst)

# Combiner X_train et y_train pour faciliter le calcul
train_data = pd.concat([X_train, y_train], axis=1)

# Calcul IV pour toutes les colonnes
iv_dict = {}
for col in X_train.columns:
    iv_dict[col] = calc_iv(train_data, col, 'flag_defaut')

# Trier les variables par IV décroissant
iv_dict = dict(sorted(iv_dict.items(), key=lambda x: x[1], reverse=True))

# Afficher les variables pertinentes avec IV > 0.02
print("Variables pertinentes (IV > 0.02) :")
selected_vars = []
for k, v in iv_dict.items():
    if v >= 0.02:
        selected_vars.append(k)
        print(f"{k}: IV = {v:.4f}")

# Créer X_train et X_test avec uniquement les variables sélectionnées
X_train_selected = X_train[selected_vars]
X_test_selected  = X_test[selected_vars]

import pandas as pd
import numpy as np

def calc_iv(df, feature, target, bins=10):
    """
    Calcule l'Information Value pour une variable continue ou catégorielle.
    """
    lst = []
    df_copy = df.copy()

    # Si variable numérique, on la binne
    if df_copy[feature].dtype.kind in 'bifc':
        df_copy[feature] = pd.qcut(df_copy[feature], q=bins, duplicates='drop')

    for val in df_copy[feature].unique():
        df_val = df_copy[df_copy[feature] == val]
        good = ((df_val[target] == 0).sum()) / ((df_copy[target] == 0).sum())
        bad  = ((df_val[target] == 1).sum()) / ((df_copy[target] == 1).sum())
        woe = np.log((good + 0.0001) / (bad + 0.0001))  # éviter div par 0
        iv = (good - bad) * woe
        lst.append(iv)

    return sum(lst)

# Combiner X_train et y_train
train_data = pd.concat([X_train, y_train], axis=1)

# Calcul IV pour toutes les colonnes
iv_dict = {col: calc_iv(train_data, col, 'flag_defaut') for col in X_train.columns}

# Trier les variables par IV décroissant
iv_dict = dict(sorted(iv_dict.items(), key=lambda x: x[1], reverse=True))

# Sélection des variables pertinentes (IV > 0.02)
selected_vars = [k for k, v in iv_dict.items() if v >= 0.02]

# Créer X_train_selected et X_test_selected
X_train_selected = X_train[selected_vars]
X_test_selected  = X_test[selected_vars]

# --- EXPORTER EN EXCEL ---
with pd.ExcelWriter("resultats_iv_train_test.xlsx", engine="openpyxl") as writer:
    # Feuille 1 : IV
    iv_df = pd.DataFrame(list(iv_dict.items()), columns=['Variable', 'IV'])
    iv_df.to_excel(writer, sheet_name='IV_variables', index=False)

    # Feuille 2 : X_train_selected
    X_train_selected.to_excel(writer, sheet_name='X_train_selected', index=False)

    # Feuille 3 : X_test_selected
    X_test_selected.to_excel(writer, sheet_name='X_test_selected', index=False)

print("Export terminé : fichier 'resultats_iv_train_test.xlsx' créé avec 3 feuilles.")

files.download("resultats_iv_train_test.xlsx")

# Matrice de corrélation
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,10))
sns.heatmap(X_train_selected.corr(), annot=True, cmap='coolwarm')
plt.title("Matrice de corrélation des variables explicatives")
plt.show()

# Exporter en Excel
corr_matrix = X_train_selected.corr()
corr_matrix.to_excel("correlation_variables.xlsx", sheet_name="Correlation", index=True)

print("Export terminé : fichier 'correlation_variables.xlsx' créé.")

files.download("correlation_variables.xlsx")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import numpy as np
# Initialiser le modèle
log_reg = LogisticRegression(
    max_iter=1000,
    solver='lbfgs'
)

# Entraînement
log_reg.fit(X_train_selected, y_train)

# Probabilités prédites pour la classe 1 (défaut)
y_pred_proba = log_reg.predict_proba(X_test_selected)[:,1]

# Prédiction binaire avec seuil 0.5
y_pred = (y_pred_proba >= 0.5).astype(int)

# AUC
auc_score = roc_auc_score(y_test, y_pred_proba)
print(f"AUC: {auc_score:.4f}")

# GINI = 2*AUC - 1
gini_score = 2 * auc_score - 1
print(f"GINI: {gini_score:.4f}")

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f"ROC curve (AUC = {auc_score:.4f})")
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- 1️⃣ Matrice de confusion ---
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print("Matrice de confusion :")
print(cm)
print(f"\nTrue Negatives (TN): {tn}")
print(f"False Positives (FP): {fp}")
print(f"False Negatives (FN): {fn}")
print(f"True Positives (TP): {tp}")

# Visualisation
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel('Prédit')
plt.ylabel('Réel')
plt.title('Matrice de confusion')
plt.show()

# --- 2️⃣ Précision, rappel, F1-score ---
print("\nRapport de classification :")
print(classification_report(y_test, y_pred, digits=4))

# --- 3️⃣ Courbe Precision-Recall ---
precision, recall, thresholds = precision_recall_curve(y_test, y_pred_proba)
ap_score = average_precision_score(y_test, y_pred_proba)

plt.figure(figsize=(7,5))
plt.plot(recall, precision, color='b', label=f'Average Precision = {ap_score:.4f}')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Courbe Precision-Recall')
plt.legend()
plt.grid(True)
plt.show()

# Probabilité de défaut pour l'ensemble test
y_pred_proba = log_reg.predict_proba(X_test_selected)[:,1]

# Ajouter au DataFrame test
df_scores = X_test_selected.copy()
df_scores['flag_defaut'] = y_test
df_scores['PD'] = y_pred_proba

# Aperçu
df_scores.head()

# Paramètres
BaseScore = 600
PDO = 20

# Conversion PD -> score
df_scores['Score'] = BaseScore + PDO * np.log((1 - df_scores['PD']) / df_scores['PD'])

# Coefficients et variables
coef_df = pd.DataFrame({
    'variable': X_train_selected.columns,
    'coef': log_reg.coef_[0]
}).sort_values(by='coef', ascending=False)

print(coef_df)